platform :ios, '6.0'
pod 'AFNetworking', '~> 1.2.1'
pod 'MagicalRecord', '~> 2.1'
pod 'BButton', '~> 2.0.0'
pod 'SVProgressHUD', '~> 0.9'
pod 'Facebook-iOS-SDK', '~> 3.5.1'
pod 'HTAutocompleteTextField', '~> 1.1.2'
pod 'ViewDeck', '~> 2.2.11'
pod 'objectiveflickr', '~> 2.0.2'

